### ISSUE TITLE
Pixelation

### ISSUE THREAD

**Issue by SimonMGS** [redhoot-dev/Godot-Open-World-Demo#2]
I think the project looks very impressive, but I'm curious about the heavy pixelation. Is this some fundamental limitation of the Godot engine, or is it simply a matter of using low quality to keep performance up?

**Comment by redhoot-dev** [comment]
Its intentional, I preferred the non-filtered textures. As it gave a realistic feel from a far but a retro-gamey feel up close. Like a painting, the details up close arent important, more about the broader strokes as a whole. 

There's no limitation to texture size or filtering in Godot as far as I know, and its not done due to any performance issues. It runs great with higher quality / larger textures too. But in this instance the textures are baked down to a single 4k map. 

When Godot4.0 beta drops I plan on re-visiting the landscape with larger datasets and textures done through the shaders instead of having a single monolithic texture.

**Comment by SimonMGS** [comment]
Great, thanks for the response. 

I'll close this now.
